services:
  mongo:
    image: mongo:7
    container_name: tmdb-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - kadracoon-net

  web:
    build:
      context: .
    container_name: tmdb-sync
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app/app
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - kadracoon-net

volumes:
  mongo_data:

networks:
  kadracoon-net:
    external: true